"""Rendering: rich terminal output and markdown reports."""

from __future__ import annotations

from datetime import date

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from auditor.models import AuditReport, Severity

SEVERITY_STYLES = {
    Severity.CRITICAL: "bold red",
    Severity.HIGH: "red",
    Severity.MEDIUM: "yellow",
    Severity.LOW: "cyan",
    Severity.INFO: "dim",
}

GRADE_STYLES = {"A": "bold green", "B": "green", "C": "yellow", "D": "red", "F": "bold red"}


def render_terminal(report: AuditReport, console: Console | None = None) -> None:
    console = console or Console()

    grade_style = GRADE_STYLES.get(report.grade, "white")
    console.print()
    console.print(
        Panel(
            f"[{grade_style}]{report.grade}[/]  {report.overall_score}/100\n\n{report.summary}",
            title=f"[bold]{report.repo}[/]",
            subtitle="code-compliance-auditor",
            border_style=grade_style,
        )
    )

    scores = Table(show_header=True, header_style="bold", box=None, pad_edge=False)
    scores.add_column("Agent")
    scores.add_column("Score", justify="right")
    scores.add_column("Findings", justify="right")
    scores.add_column("Checks", justify="right")
    for result in (report.security, report.compliance, report.debt):
        scores.add_row(
            result.agent,
            str(result.score),
            str(len(result.findings)),
            str(result.checks_run),
        )
    console.print()
    console.print(scores)

    if not report.all_findings:
        console.print("\n[green]No findings.[/]")
        return

    table = Table(title="\nFindings", show_header=True, header_style="bold", box=None)
    table.add_column("Sev", width=9)
    table.add_column("Rule", width=8)
    table.add_column("Title")
    table.add_column("Path", overflow="fold")

    ordered = sorted(
        report.all_findings,
        key=lambda f: (list(Severity).index(f.severity), f.rule_id),
    )
    for f in ordered:
        table.add_row(
            f"[{SEVERITY_STYLES[f.severity]}]{f.severity.value}[/]",
            f.rule_id,
            f.title,
            f.path or "-",
        )
    console.print(table)

    if report.priorities:
        console.print("\n[bold]Fix first[/]")
        for i, f in enumerate(report.priorities, 1):
            console.print(f"  {i}. [{SEVERITY_STYLES[f.severity]}]{f.title}[/] -- {f.remediation}")
    console.print()


def render_markdown(report: AuditReport) -> str:
    lines = [
        f"# Compliance Audit: {report.repo}",
        "",
        f"**Grade:** {report.grade}  |  **Score:** {report.overall_score}/100  |  "
        f"**Date:** {date.today().isoformat()}",
        "",
        report.summary,
        "",
        "## Scores",
        "",
        "| Agent | Score | Findings | Checks |",
        "|-------|-------|----------|--------|",
    ]
    for result in (report.security, report.compliance, report.debt):
        lines.append(
            f"| {result.agent} | {result.score}/100 | {len(result.findings)} | {result.checks_run} |"
        )

    lines.extend(["", "## Findings", ""])
    if report.all_findings:
        lines.extend(["| Severity | Rule | Title | Path |", "|----------|------|-------|------|"])
        ordered = sorted(
            report.all_findings,
            key=lambda f: (list(Severity).index(f.severity), f.rule_id),
        )
        for f in ordered:
            lines.append(
                f"| {f.severity.value} | {f.rule_id} | {f.title} | `{f.path or '-'}` |"
            )
    else:
        lines.append("No findings.")

    if report.priorities:
        lines.extend(["", "## Fix first", ""])
        for i, f in enumerate(report.priorities, 1):
            lines.append(f"{i}. **{f.title}** ({f.severity.value}) -- {f.remediation}")

    lines.extend(
        [
            "",
            "---",
            "",
            "*Generated by [code-compliance-auditor]"
            "(https://github.com/brianpelow/code-compliance-auditor). "
            "All findings are deterministic and reproducible.*",
        ]
    )
    return "\n".join(lines)