"""Renders PortfolioState as STATE.md.

Kept separate from collection so every rendering path is testable with fixture
data and no network. Output is deterministic apart from the timestamp.
"""

from __future__ import annotations

from auditor.state import (
    CATEGORY_ORDER,
    STRUCTURAL_EXCEPTIONS,
    PortfolioState,
)


def render(state: PortfolioState) -> str:
    lines: list[str] = [
        "# Portfolio State",
        "",
        f"**Generated:** {state.generated_at}",
        "**Source:** live GitHub API and code-compliance-auditor",
        "",
        "This file is machine-generated on a nightly schedule. Do not edit it by hand;",
        "changes will be overwritten. Every number here is measured rather than asserted,",
        "which is why it cannot drift the way a hand-maintained document does.",
        "",
        "---",
        "",
    ]

    lines.extend(_summary(state))
    lines.extend(_action_items(state))
    lines.extend(_catalog(state))
    lines.extend(_surfaces(state))
    lines.extend(_ci(state))

    lines.extend(
        [
            "---",
            "",
            "*Generated by [code-compliance-auditor]"
            "(https://github.com/brianpelow/code-compliance-auditor). "
            "Grades are deterministic: the same repository snapshot always produces "
            "the same score.*",
            "",
        ]
    )
    return "\n".join(lines)


def _summary(state: PortfolioState) -> list[str]:
    grades = ", ".join(f"{n} {g}" for g, n in state.grade_counts.items()) or "none"
    healthy = sum(1 for s in state.surfaces if s.healthy)

    return [
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Public repos | {len(state.repos)} |",
        f"| Scheduled agents | {state.scheduled_agents} |",
        f"| Audit average | {state.average_score}/100 |",
        f"| Grade distribution | {grades} |",
        f"| Live surfaces healthy | {healthy} of {len(state.surfaces)} |",
        f"| Repos below B | {len(state.below_b)} |",
        "",
    ]


def _action_items(state: PortfolioState) -> list[str]:
    items: list[str] = []

    for name in state.uncategorized:
        items.append(
            f"**{name}** is not in the category map. "
            "Add it to `CATEGORIES` in `src/auditor/state.py` and to the dashboard catalog."
        )

    for surface in state.unhealthy_surfaces:
        if surface.error:
            items.append(f"**{surface.url}** unreachable: {surface.error}")
        elif surface.status != 200:
            items.append(f"**{surface.url}** returned HTTP {surface.status}")
        elif surface.non_ascii:
            items.append(
                f"**{surface.url}** contains {surface.non_ascii} non-ASCII character(s). "
                "Encoding corruption may be recurring; convert literals to HTML entities."
            )

    for repo in state.failing_ci:
        items.append(f"**{repo}** CI is {state.ci_status[repo]}")

    for repo in state.below_b:
        items.append(f"**{repo.name}** scores {repo.score}/100 (grade {repo.grade})")

    for repo in state.repos:
        if not repo.ok:
            items.append(f"**{repo.name}** could not be audited: {repo.error}")

    if not items:
        return [
            "## Action items",
            "",
            "None. All surfaces healthy, all repos categorized, no repo below grade B,",
            "all CI green.",
            "",
        ]

    lines = ["## Action items", ""]
    lines.extend(f"- {item}" for item in items)
    lines.append("")
    return lines


def _catalog(state: PortfolioState) -> list[str]:
    lines = ["## Repository catalog", ""]

    by_category: dict[str, list] = {}
    for repo in state.repos:
        by_category.setdefault(repo.category, []).append(repo)

    for category in CATEGORY_ORDER:
        repos = by_category.get(category)
        if not repos:
            continue
        lines.extend(
            [
                f"### {category}",
                "",
                "| Repo | Grade | Score | Findings |",
                "|------|-------|-------|----------|",
            ]
        )
        for repo in sorted(repos, key=lambda r: r.name.lower()):
            if repo.ok:
                note = ""
                if repo.name in STRUCTURAL_EXCEPTIONS:
                    note = " *"
                lines.append(
                    f"| {repo.name}{note} | {repo.grade} | {repo.score} | {repo.findings} |"
                )
            else:
                lines.append(f"| {repo.name} | - | - | audit failed |")
        lines.append("")

    if any(r.name in STRUCTURAL_EXCEPTIONS for r in state.repos):
        lines.extend(["**\\*** Structural exception:", ""])
        for name, reason in sorted(STRUCTURAL_EXCEPTIONS.items()):
            if any(r.name == name for r in state.repos):
                lines.append(f"- `{name}` &mdash; {reason}")
        lines.append("")

    return lines


def _surfaces(state: PortfolioState) -> list[str]:
    lines = [
        "## Live surfaces",
        "",
        "| URL | Status | Encoding |",
        "|-----|--------|----------|",
    ]
    for s in state.surfaces:
        if s.error:
            lines.append(f"| {s.url} | error | {s.error} |")
        else:
            encoding = "clean" if s.non_ascii == 0 else f"{s.non_ascii} non-ASCII"
            lines.append(f"| {s.url} | {s.status} | {encoding} |")
    lines.append("")
    return lines


def _ci(state: PortfolioState) -> list[str]:
    if not state.ci_status:
        return []
    lines = ["## CI status", "", "| Repo | Latest run |", "|------|------------|"]
    for repo in sorted(state.ci_status):
        lines.append(f"| {repo} | {state.ci_status[repo]} |")
    lines.append("")
    return lines